services:
  app:
    build: .
    container_name: is-app
    depends_on:
      - minio
    environment:
      - TEMPORAL_ADDR=temporal:7233
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USESSL=false
      - TASK_QUEUE=images-storage
    networks:
      - is-network
      - temporal-network

  minio:
    image: minio/minio:latest
    container_name: is-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    networks:
      - is-network
    command: server /data --console-address ":9001"

volumes:
  miniodata:
    driver: local

networks:
  is-network:
    driver: bridge
    name: is-network
  temporal-network:
    external: true
